CREATE TABLE "CHA_1 step 1" AS SELECT A.au_id AS "AUTHOR ID",
TI.title_id AS "TITLE ID",
A.au_lname AS "LAST NAME",
A.au_fname AS "FIRST NAME",
T.price * S.qty * 
T.royalty / 100 * TI.royaltyper / 100
AS "ROYALTIES"  
FROM authors A 
INNER JOIN titleauthor TI 
ON A.au_id = TI.au_id 
INNER JOIN sales S 
ON TI.title_id = S.title_id 
INNER JOIN titles T 
ON T.title_id = TI.title_id
ORDER BY "ROYALTIES" DESC;

CREATE TABLE "CHA_1 step 2" AS SELECT CH."AUTHOR ID",
CH."TITLE ID",
CH."LAST NAME",
CH."FIRST NAME",
SUM(CH.ROYALTIES) AS "AGGREATED ROYALTIES"
FROM "CHA_1 step 1" CH
GROUP BY CH."AUTHOR ID" , CH."TITLE ID"
ORDER BY "AGGREATED ROYALTIES" DESC;

CREATE TABLE "CHA_1 step 3" AS SELECT CHA."AUTHOR ID",
CHA."TITLE ID",
CHA."LAST NAME",
CHA."FIRST NAME",
T.advance + CHA."AGGREATED ROYALTIES" AS "TOTAL"
FROM "CHA_1 step 2" CHA INNER JOIN titles T
ON CHA."TITLE ID" = T.title_id
ORDER BY "TOTAL" DESC
LIMIT 3;

SELECT
ADVANCE + "AGGREATED ROYALTIES" AS "TOTAL"
FROM 
(SELECT 
CH."AUTHOR ID",
CH."TITLE ID",
CH."LAST NAME",
CH."FIRST NAME",
T.advance AS "ADVANCE",
SUM(CH.ROYALTIES) AS "AGGREATED ROYALTIES"
FROM
"CHA_1 step 1" CH INNER JOIN 
titles T
ON CH."TITLE ID" = T.title_id
GROUP BY CH."AUTHOR ID" , CH."TITLE ID") AS "Derived"
ORDER BY "TOTAL" DESC;

CREATE TABLE most_profiting_authors AS 
SELECT
"AUTHOR ID",
ADVANCE + "AGGREATED ROYALTIES" AS "TOTAL"
FROM 
(SELECT 
CH."AUTHOR ID",
CH."TITLE ID",
CH."LAST NAME",
CH."FIRST NAME",
T.advance AS "ADVANCE",
SUM(CH.ROYALTIES) AS "AGGREATED ROYALTIES"
FROM
"CHA_1 step 1" CH INNER JOIN 
titles T
ON CH."TITLE ID" = T.title_id
GROUP BY CH."AUTHOR ID" , CH."TITLE ID") AS "Derived"
ORDER BY "TOTAL" DESC
LIMIT 3;